<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "simply_responsive_content"
 *
 * Auto generated by Extension Builder 2013-05-15
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Simply Responsive Content',
	'description' => 'Fine grained responsive settings for tt_content elements. To be used with ZURB Foundation.',
	'category' => 'fe',
	'author' => 'Henjo Hoeksma',
	'author_email' => 'hphoeksma@stylence.nl',
	'author_company' => 'Stylence',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.2',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0-6.1.99',
			'fluid' => '6.0-6.1.99',
			'typo3' => '6.0-6.1.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>